#ifndef BOOKSTORE_SRC_FILESYSTEM_DEFAULTCONST_H
#define BOOKSTORE_SRC_FILESYSTEM_DEFAULTCONST_H
const int string_size = 100;
const int max_node_size = 7;
#endif // BOOKSTORE_SRC_FILESYSTEM_DEFAULTCONST_H