#ifndef TRAINTICKETSYSTEM_2022_SRC_TOOLS_CONST_VALUE_H
#define TRAINTICKETSYSTEM_2022_SRC_TOOLS_CONST_VALUE_H
#include "const_value.h"
// int kDefaultStrLength = 200;
#endif  // TRAINTICKETSYSTEM_2022_SRC_TOOLS_CONST_VALUE_H